package eu.uniga.EmojiService.ResourcePack;

import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.List;
import java.util.Timer;

import eu.uniga.EmojiService.BitmapGenerator;
import net.dv8tion.jda.api.entities.Emote;
import net.dv8tion.jda.api.entities.Guild;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.imageio.ImageIO;

public class Service
{
	private final Logger _logger = LoggerFactory.getLogger(this.getClass().getName());
	private static final String AtlasName = "discord-emoji";
	public static final Path ResourcePackLocation = Paths.get("resource-pack.zip");
	private final Set<Guild> _servers = new HashSet<>();
	private final Object _serversLock = new Object();
	private final Set<Emote> _emotes = new HashSet<>();
	private final Object _emotesLock = new Object();
	private final Timer _timer;
	
	private BufferedImage _emoteBitmapAtlas = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
	private int[][] _emoteCodepointAtlas = new int[0][0];
	private Map<Integer, String> _emoteTranslation = new HashMap<>();
	
	public Service()
	{
		_timer = new Timer(true);
	}
	
	public void AddServer(Guild server)
	{
		_servers.add(server);
	}
	
	public void Start()
	{
		// TODO: Move period to config
		_timer.scheduleAtFixedRate(new Grabber(), 0, 2 * 60 * 60* 1000);
		//_timer.scheduleAtFixedRate(new Grabber(), 0, 10 * 1000);
	}
	
	public void Stop()
	{
		_timer.cancel();
		_timer.purge();
	}
	
	private byte[] ToByteArray(RenderedImage image) throws IOException
	{
		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		ImageIO.write(image, "png", stream);
		stream.close();
		
		return stream.toByteArray();
	}
	
	private @NotNull String Utf16ToEscapedString(int utf16)
	{
		String out = "";
		
		short left = (short)((utf16 & 0xFFFF0000) >> 16);
		short right = (short)utf16;
		
		if (left != 0) out += String.format("\\u%s", String.format("%04x", left));
		out += String.format("\\u%s", String.format("%04x", right));
		
		return out;
	}
	
	private byte[] FormatToByteArray(int[][] codepointAtlas)
	{
		// TODO: move to file
		String json = "{\n" + "  \"providers\": [\n" + "    {\n" + "      \"type\": \"bitmap\",\n" + "      \"file\": \"minecraft:font/%name%.png\",\n" + "      \"ascent\": 7,\n" + "      \"chars\": [\n" + "        %chars%\n" + "      ]\n" + "    }\n" + "  ]\n" + "}";
		StringBuilder formattedAtlas = new StringBuilder();
		
		for (int y = 0; y < codepointAtlas.length; y++)
		{
			formattedAtlas.append("\"");
			
			for (int x = 0; x < codepointAtlas[y].length; x++)
			{
				formattedAtlas.append(Utf16ToEscapedString(codepointAtlas[y][x]));
			}
			
			formattedAtlas.append("\"");
			if (y < codepointAtlas.length - 1) formattedAtlas.append(",");
			formattedAtlas.append(System.lineSeparator());
		}
		
		json = json.replace("%name%", AtlasName);
		json = json.replace("%chars%", formattedAtlas.toString());
		
		return json.getBytes();
	}
	
	private byte[] GetPackMCMeta()
	{
		// TODO: move to file
		String json = "{\n" + "\t\"pack\": {\n" + "\t\t\"pack_format\": 5,\n" + "\t\t\"description\": [\n" + "\t\t\t{\n" + "\t\t\t\t\"text\": \"Autogenerated\",\n" + "\t\t\t\t\"bold\": true,\n" + "\t\t\t\t\"color\": \"#FF0000\"\n" + "\t\t\t}\n" + "\t\t]\n" + "\t}\n" + "}";
		
		return json.getBytes();
	}
	
	private void CreateZip()
	{
		try
		{
			byte[] atlas = ToByteArray(_emoteBitmapAtlas);
			
			Zip zip = new Zip();
			zip.Add("assets/minecraft/textures/font/" + AtlasName + ".png", atlas);
			zip.Add("assets/minecraft/font/default.json", FormatToByteArray(_emoteCodepointAtlas));
			zip.Add("pack.mcmeta", GetPackMCMeta());
			zip.Finish();
		}
		catch (IOException e)
		{
			_logger.warn("Error creating resource pack", e);
		}
	}
	
	public class Grabber extends TimerTask
	{
		@Override
		public void run()
		{
			// TODO: on emoji remove
			_emotes.clear();
			int added = GetEmotes();
			if (added == 0) return;
			
			synchronized (_emotesLock)
			{
				BitmapGenerator bitmapGenerator = new BitmapGenerator(_emotes);
				
				_emoteBitmapAtlas = bitmapGenerator.GetEmoteBitmapAtlas();
				_emoteCodepointAtlas = bitmapGenerator.GetEmoteCodepointAtlas();
				_emoteTranslation = bitmapGenerator.GetEmoteTranslation();
			}
			
			CreateZip();
		}
		
		private int GetEmotes()
		{
			int added = 0;
			
			synchronized (_serversLock)
			{
				for (Guild server : _servers)
				{
					added += GetEmotes(server);
				}
			}
			
			return added;
		}
		
		private int GetEmotes(Guild server)
		{
			List<Emote> emotes = server.getEmotes();
			int added = 0;
			
			synchronized (_emotesLock)
			{
				for (Emote emote : emotes)
				{
					added += _emotes.add(emote) ? 1 : 0;
				}
			}
			
			return added;
		}
	}
}